config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'

  get 'about' => 'home#about'

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include HasGravatar
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar

  def gravatar
    "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

app/models/question.rb
class Question < ApplicationRecord
  include HasGravatar
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:answer][:question_id])
    answer = question.answers.create(answer_params)

    MainMailer.notify_question_author(answer).deliver_later

    session[:current_user_email] = params[:answer][:email]
    redirect_to question
  end

  def answer_params
    params.require(:answer).permit(:email, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # hey
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
    
  end

  def temp
    redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    Question.create(question_params)
    session[:current_user_email] = params[:question][:email]

    redirect_to root_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
  end

  private

  def question_params
    params.require(:question).permit(:email, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_email
    session[:current_user_email]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Hey Question And Answer For This</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li><%= current_user_email %></li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <button class="btn btn-success my-2 my-sm-0" type="button" data-toggle="modal" data-target="#exampleModalCenter">Ask Question</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="newAnswerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Write A Answer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/answers") do %>
          <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="answer_body">Answer</label>
            <textarea class="form-control" name="question" id="answer_body" rows="3"></textarea>
          </div>

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ask A Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/questions") do %>
          <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" class="form-control" name="question[email]" value="<%= current_user_email %>" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="question_body">Example textarea</label>
            <textarea class="form-control" name="question[body]" id="question_text" rows="3"></textarea>
          </div>

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  </div>
</div>

<ul class="list-unstyled boxes">
  <% @questions.each do |q| %>
  <li class="media" data-target="<%= question_path(q) %>">
    <img class="mr-3" src="<%= q.gravatar %>"
         alt="Generic placeholder image" height="128" width="128px">
    <div class="media-body">
      <h5 class="mt-0 mb-1"><%= q.email %></h5>
      <div class="time"><%= time_ago_in_words q.created_at %> ago</div>
      <%= q.body %>
    </div>
    <div>
      <a href="<%= question_path(q) %>" class="btn btn-success btn-xs">View Answers</a>
    </div>
  </li>
  <% end %>

  <% if @questions.empty? %>
    <div class="alert alert-primary" role="alert">
      No Questions Found Create One !
    </div>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HUU</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'home/new_question_form' %>
  <%= render 'home/navbar' %>

  <div class="container">
    <%= yield %>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/questions/_new_answer_form.html.erb
<div class="modal fade" id="newAnswerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Write A Answer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/answers") do %>
          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
          <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" class="form-control" name="answer[email]" value="<%= current_user_email %>"
                   placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="answer_body">Answer</label>
            <textarea class="form-control" name="answer[body]"  rows="3"></textarea>
          </div>

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="lead">
  <ul class="list-unstyled">
    <li class="media">
      <img class="mr-3" src="<%= @question.gravatar %>"
           alt="Generic placeholder image" height="128" width="128px">
      <div class="media-body">
        <h5 class="mt-0 mb-1"><%= @question.email %></h5>
        <%= @question.body %>
      </div>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <div>
      <button class="btn btn-success btn-xs" data-toggle="modal" data-target="#newAnswerModal">Submit New Answer</button>
    </div>
    <%= render 'new_answer_form' %>
    <% @answers.each do |answer| %>
    <li class="media">
      <img class="mr-3" src="<%= answer.gravatar %>"
           alt="Generic placeholder image" height="128" width="128px">
      <div class="media-body">
        <h5 class="mt-0 mb-1"><%= answer.email %></h5>
        <div><%= time_ago_in_words answer.created_at %> ago</div>
        <%= answer.body %>
      </div>
    </li>
    <% end %>
    <% if @answers.empty? %>
      <div class="alert alert-primary" role="alert">
        No Answers Found Create One !
      </div>
    <% end %>
  </div>
</div>